# Generated by Django 4.1.7 on 2023-05-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('S_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_Name', models.CharField(max_length=30)),
            ],
        ),
    ]
